# Generated by Django 2.0.6 on 2018-06-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('Bug Report', 'Bug Report'), ('Personnel Account Issue', 'Personnel Account Issue'), ('Feature Request', 'Feature Request'), ('Other', 'Other')], default='Bug Report', max_length=23),
        ),
        migrations.AddField(
            model_name='note',
            name='domain',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=7),
        ),
        migrations.AddField(
            model_name='note',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Under Process', 'Under Process'), ('Already Working', 'Already Working'), ('Infeasible', 'Infeasible'), ('Resolved', 'Resolved')], default='Received', max_length=15),
        ),
    ]
