# Generated by Django 2.0.6 on 2018-06-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180611_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='status',
            new_name='statusi',
        ),
    ]
